export interface Student {
    surname: string,
    firstName: string,
    secondName: string,
    dob: Date,
    board: string,
    class: string,
    gender: string,
    address: string,
    fatherNumber: number,
    motherNumber: number,
    otherNumber: number,
    whatsAppNumber: number,
    email: string,
    parentsOccupation: string,
    parentsOccupationAddress: string,
    presentSchool: string,
    previousResult: string,
    password: string,
    token?: string,
    isAdmin: boolean,
    _id: string,
    isSelected: boolean,
    marks: string
}